# Model and training configuration
model:
  input_size: 299 # Number of 2D keypoints per frame
  hidden_size: 512
  num_layers: 2
  dropout: 0.3

training:
  batch_size: 16
  num_epochs: 30
  learning_rate: 0.001
  teacher_forcing_ratio: 0.5
  max_seq_length: 100

paths:
  data_dir: "data/processed/"
  vocab_file: "data/vocab.json"
  save_model_path: "checkpoints/model.pth"

device: "cpu"
